package bankExample;

/**
 * Bank/Account.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from Bank.idl
 * Monday, October 28, 2013 5:49:03 PM CET
 */
public final class Account //implements org.omg.CORBA.portable.IDLEntity
{
   public int accountNo = (int) 0;
   public String name = null;
   public double balance = (double) 0;

   public Account() {}

   public Account(int accountNo, String name, double balance) {
      this.accountNo = accountNo;
      this.name = name;
      this.balance = balance;
   }
}